### ISSUE TITLE
Add docker container name to docker.discovery 

### ISSUE THREAD

**Issue by netflash** [jangaraj/Zabbix-Docker-Monitoring#6]
Hi, is it possible to add 
docker container "name" (in this example name is "docker_nginx" ) to discovery keys?
so it could be more human readable in items/triggers.
```
docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS                                                 NAMES
b22f3f28a36e        dockerfile/nginx:latest   "nginx"                5 hours ago         Up 5 hours          443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:8001->8001/tcp   docker_nginx
```

**Comment by jangaraj** [comment]
I agree.  Question is how to read docker data structure from user space?
Some implementation use some virt libraries/utilities - but the main stopper here is root permissions, because zabbix agent has usually only user zabbix permissions. Still I didn't find any reasonable solution. The similar root permission problem is with network metrics :(.

**Comment by netflash** [comment]
For such cases I usually use two external scripts.

/etc/zabbix/zabbix_agentd.conf
```
UserParameter=param[*],/opt/zabbix/bin/script1 \$1 \$2 \$3
```
/etc/sudoers.d/zabbix
```
zabbix ALL = (root) NOPASSWD: /opt/zabbix/bin/script2 *
```

zabbix_agent run "script1" and from inside this script it calls "sudo script2"

**Comment by jangaraj** [comment]
But this is module ;-) = no shell execution and native C performance. I can do everything by using userparameters script with sudo, but I would like to keep it with native performance as much as possible. The best solution is to use some docker lib C library (I didn't find anything), which will be included in this module and it will provide access to full docker data structure.

**Comment by netflash** [comment]
Is root permission is needed? Maybe that's enought to add zabbix to docker group ?

**Comment by jangaraj** [comment]
Work in progress. 

Docker unix socket API will be used - https://docs.docker.com/reference/api/docker_remote_api/
*By default the Docker daemon listens on unix:///var/run/docker.sock and the client must have root access to interact with the daemon.*
=> root permission for zabbix-agent will be required (*AllowRoot=1* in zabbix_agentd.conf)

I'm trying to parse JSON in my code at the moment. 
When it'll be implemented, then more container metrics will be available and module can go to beta phase.

**Comment by netflash** [comment]
As I know - root permissions are not needed.
It's enough to add zabbix user to docker group and restart zabbix-agent.

**Comment by jangaraj** [comment]
Yes, you are true:
[root@dev ~]# ls -lah /var/run/docker.sock
srw-rw---- 1 root docker 0 Mar  5 23:55 /var/run/docker.sock

Done - implemented. Feel free to test and let me know if it's OK.

**Comment by netflash** [comment]
Hi, not working for me :-(
1. I can't import template - probably cause my zabbix server is 2.2.8, so I manual added items to discovery.
2. my docker version is 1.5.0
3. all my containers linked with some others, maybe this is the reason.
here's some log

```
Docker's socket response:[{"Command":"nginx","Created":1426152751,"Id":"3bae6a35de7f5926162c01498427267ae4523c22914aea8fe97d17337cd0709f","Image":"docker
file/nginx:latest","Names":["/docker_nginx"],"Ports":[{"IP":"0.0.0.0","PrivatePort":80,"PublicPort":80,"Type":"tcp"},{"IP":"0.0.0.0","PrivatePort":8001,"PublicPort":8001,"Type":"tcp
"},{"PrivatePort":443,"Type":"tcp"}],"Status":"Up About an hour"}
====== cut lot of containers here ========
]
  6662:20150312:144148.481 Parsed container name(s): docker_nginx
  6662:20150312:144148.481 Cannot find the "Id" array in the received JSON object
  6662:20150312:144148.481 Parsed container name(s): demo-kirsan","/docker_nginx/demo-kirsan
  6662:20150312:144148.481 Cannot find the "Id" array in the received JSON object
```

**Comment by netflash** [comment]
Also it looks like function "zbx_docker_perm" is not working.
So discovery through socket only working when zabbix-agent run as root with AllowRoot=1.

As I get - because of my zabbix user is member of 3 groups - I sent another PR to fix typo.
And also my zabbix-agent is running from different username - I changed in to that username and it works for me, but how to make that more common - I don't know :-(

**Comment by jangaraj** [comment]
if (getgrouplist("zabbix", geteuid(), groups, &ngroups) == -1) 
Yes, zabbix id is hardcoded - it'll be detected in next version :-)

**Comment by netflash** [comment]
Yeah, that's not a big issue.
I care more about previous message and q.3

**Comment by jangaraj** [comment]
Interesting
zabbix_agentd 2.2.8:
```
 51626:20150312:183957.895 Simulated docker answer: [{"Command":"nginx","Created":1426152751,"Id":"3bae6a35de7f5926162c                                                 01498427267ae4523c22914aea8fe97d17337cd0709f","Image":"dockerfile/nginx:latest","Names":["/docker_nginx"],"Ports":[{"IP                                                 ":"0.0.0.0","PrivatePort":80,"PublicPort":80,"Type":"tcp"},{"IP":"0.0.0.0","PrivatePort":8001,"PublicPort":8001,"Type":                                                 "tcp"},{"PrivatePort":443,"Type":"tcp"}],"Status":"Up About an hour"}]
 51626:20150312:183957.895 Parsed container name(s): docker_nginx
 51626:20150312:183957.895 Parsed container id: 3bae6a35de7f5926162c01498427267ae4523c22914aea8fe97d17337cd0709f
 51626:20150312:183957.895 Sending back [{
        "data":[
                {
                        "{#FCONTAINERID}":"3bae6a35de7f5926162c01498427267ae4523c22914aea8fe97d17337cd0709f",
                        "{#HCONTAINERID}":"docker_nginx"}]}]
 51626:20150312:183957.895 listener #3 [waiting for connection]
```
zabbix_agentd 2.4.4:
```
 51769:20150312:184311.194 In zbx_module_docker_discovery_extended()
 51769:20150312:184311.195 Simulated docker answer: [{"Command":"nginx","Created":1426152751,"Id":"3bae6a35de7f5926162c01498427267ae4523c22914aea8fe97d17337cd0709f","Image":"dockerfile/nginx:latest","Names":["/docker_nginx"],"Ports":[{"IP":"0.0.0.0","PrivatePort":80,"PublicPort":80,"Type":"tcp"},{"IP":"0.0.0.0","PrivatePort":8001,"PublicPort":8001,"Type":"tcp"},{"PrivatePort":443,"Type":"tcp"}],"Status":"Up About an hour"}]
 51769:20150312:184311.195 Parsed container name(s): docker_nginx
 51769:20150312:184311.195 Parsed container id: 3bae6a35de7f5926162c01498427267ae4523c22914aea8fe97d17337cd0709f
 51769:20150312:184311.195 Sending back [{"data":[{"{#FCONTAINERID}":"3bae6a35de7f5926162c01498427267ae4523c22914aea8fe97d17337cd0709f","{#HCONTAINERID}":"docker_nginx"}]}]
 51769:20150312:184311.195 listener #2 [waiting for connection]
```
Could you provide pastebin.com of your log and agent version please? I'm interesting how json docker answer looks.

**Comment by netflash** [comment]
1) import errors
```
Created: Application "Docker" on "Template App Docker - active".
mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
SQL error [ORA-00984: column not allowed here] in [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Running containers','7','','','300','0','','','0','0','','0','','','','','0','','','','','',Array,'10','','docker.discovery','','11051','1','4','0',NULL,'125471')]
Incorrect value "" for unsigned int field "parent_itemid".
```
here could be some issues related only to my Oracle DB

log - http://pastebin.com/exKTH1YL

b)
my opinion - human name should be the same as "docker ps" shows - so 
it must be "demo-kirsan"

**Comment by jangaraj** [comment]
Thank you for your input @netflash 

1.) Unfortunately, I can't help you with ORA SQL error - please try to report this issue to Zabbix company.
2.) Ok, I don't see any issues in my code at the moment, but I'll try to find it and also I'll improve name of the container.

**Comment by netflash** [comment]
1) For Oracle - it's OK, not a big deal. I still thinking that it could be related to 2.4.x vs. 2.2.x.
2) if you need any help with testing new version - let me know.

**Comment by jangaraj** [comment]
New version committed. Some your issues (hardcoded zabbix user, human container name) have been fixed + support for systemd docker and docker.dev key have been implemented. If you have still problem with "Id", please uncomment:
```
zabbix_log(LOG_LEVEL_WARNING, "Cannot find the \"Id\" array in the received JSON object, jp_row: %s", jp_row);
```
and then provide me pastebin debug output please.

**Comment by netflash** [comment]
Still not working. Here's a log: http://pastebin.com/aF46ExWJ

**Comment by jangaraj** [comment]
Could provide version and details about:
- OS (uname -a)
- docker (docker info, docker -v)
- zabbix agent (zabbix_agentd -v)

I would like to start your config on my localhost.

Thx.

**Comment by netflash** [comment]
Debian 7, x64, Linux hostname 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux


:~$ docker info
Containers: 93
Images: 165
Storage Driver: aufs
 Root Dir: /ssd/docker/aufs
 Backing Filesystem: <unknown>
 Dirs: 463
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 8
Total Memory: 47.26 GiB
Name: hostname
ID: BFDQ:DYJU:SWMU:4MBB:2WUB:4FRY:XVX6:CH35:TRCY:PSEU:3XCN:ZZ4D
WARNING: No memory limit support
WARNING: No swap limit support

:~$ docker -v
Docker version 1.5.0, build a8a31ef

zabbix_agentd -V
Zabbix Agent (daemon) v2.4.1 (revision 49643) (8 October 2014)
Compilation time: Nov  7 2014 12:59:43

**Comment by jangaraj** [comment]
I hope, that's fixed now. Tested with your config (Debian 7, Docker 1.5, 3.16.0-0.bpo.4-amd64) + Centos 7.
Please test and let me know.

**Comment by netflash** [comment]
Discovery is fixed, thank you very much.

is this ok ?
```
zabbix_agentd -t docker.cpu[2c1da060c5e027256eeba52108ea789ccc4449bb4f9c4e314d3bb74e73fc889d,system]
docker.cpu[2c1da060c5e027256eeba52108ea789ccc4449bb4f9c4e314d3bb74e73fc889d,system] [u|1221]
```
I mean 4 digits for result ?

**Comment by jangaraj** [comment]
Perfect. Yes cpu usage is measured in jiffies and normalized with number of online CPU. Percentage is calculated by Zabbix - it's just math. The best solution will be creating collector (as current Zabbix agent has dor CPU metrics), but I'm not sure if I can do it in shared library.
